policy_path: "g1_12dof.pt"
xml_path: "g1_12dof.xml"

# Total simulation time
simulation_dt: 0.002
control_dt: 0.02

kps: [100, 100, 100, 150, 40, 40, 100, 100, 100, 150, 40, 40]
kds: [2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2]

default_base_pos: [0, 0, 0.78, 1, 0, 0, 0]
default_joint_pos: [-0.1,  0.0,  0.0,  0.3, -0.2, 0.0, 
                  -0.1,  0.0,  0.0,  0.3, -0.2, 0.0]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]