
# interpolate to default position duration
interp_default_pos_duration: 5.0  # [sec]
hold_default_pos_duration:   5.0  # [sec]

# default joint positions
default_joint_pos: [
    0, 0, 0, 0, 0, 0,     # LHP, LHR, LHY, LKP, LAP, LAR
    0, 0, 0, 0, 0, 0,     # RHP, RHR, RHY, RKP, RAP, RAR
    0, 0, 0,              # WAY, WAR, WAP
    0, 0, 0, 0, 0, 0, 0,  # LSP, LSR, LSY, LEP, LWR, LWP, LWY
    0, 0, 0, 0, 0, 0, 0   # RSP, RSR, RSY, REP, RWR, RWP, RWY
]

# PD gains
Kp: [
    60, 60, 60, 100, 40, 40,      # LHP, LHR, LHY, LKP, LAP, LAR
    60, 60, 60, 100, 40, 40,      # RHP, RHR, RHY, RKP, RAP, RAR
    60, 40, 40,                   # WAY, WAR, WAP
    40, 40, 40, 40,  40, 40, 40,  # LSP, LSR, LSY, LEP, LWR, LWP, LWY
    40, 40, 40, 40,  40, 40, 40   # RSP, RSR, RSY, REP, RWR, RWP, RWY
]
Kd: [
    1, 1, 1, 2, 1, 1,     # LHP, LHR, LHY, LKP, LAP, LAR
    1, 1, 1, 2, 1, 1,     # RHP, RHR, RHY, RKP, RAP, RAR
    1, 1, 1,              # WAY, WAR, WAP
    1, 1, 1, 1, 1, 1, 1,  # LSP, LSR, LSY, LEP, LWR, LWP, LWY
    1, 1, 1, 1, 1, 1, 1   # RSP, RSR, RSY, REP, RWR, RWP, RWY
]
